#!/bin/sh
set -e

# This file is a modified entrypoint based upon the [original docker-php-entrypoint]
# (https://github.com/docker-library/php/blob/master/8.3/alpine3.20/fpm/docker-php-entrypoint)

# Start modification
# Check for an `init.d` folder and execute the containg scripts.
if [ -d /usr/local/bin/docker-entrypoint.d ]; then
	for f in /usr/local/bin/docker-entrypoint.d/*.sh; do
		ash "$f"
	done
fi
# End modification

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

exec "$@"
